spring:
  application:
    name: @project.artifactId@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
server:
  port: 80
info:
  version: @imooc.security.version@

imooc:
  security:
    browser:
      login-type: JSON
#      login-page: /demo-signIn.html
    code:
      image:
        width: 35
        length: 2
        url: /user/*
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent_output: true